#!/usr/bin/env bash
set -E -e -o pipefail

# Add repo specific metadata here.

BASE_IMAGE_CONFIG_KEY_PREFIX="BASE_IMAGE"

UPSTREAM_PACKAGE_NAME="Opengist/Go/nvm/Node.js"
UPSTREAM_OPENGIST_VERSION_CONFIG_KEY="OPENGIST_VERSION"
UPSTREAM_OPENGIST_GIT_REPO="https://github.com/thomiceli/opengist"
UPSTREAM_GO_IMAGE_NAME_CONFIG_KEY="GO_IMAGE_NAME"
UPSTREAM_GO_IMAGE_TAG_CONFIG_KEY="GO_IMAGE_TAG"
UPSTREAM_GO_IMAGE_PATTERN="^[0-9]+\.[0-9]+\.[0-9]+-go-.+$"
UPSTREAM_NVM_VERSION_CONFIG_KEY="NVM_VERSION"
UPSTREAM_NODEJS_VERSION_CONFIG_KEY="IMAGE_NODEJS_VERSION"
UPSTREAM_NVM_CHECKSUM_CONFIG_KEY="NVM_SHA256_CHECKSUM"
UPSTREAM_NVM_GIT_REPO="https://github.com/nvm-sh/nvm"

RELEASE_PACKAGE_NAME="Opengist"
RELEASE_PACKAGE_VERSION_CONFIG_KEY="OPENGIST_VERSION"
RELEASE_TAG_PACKAGE_NAME="opengist"

TEST_TYPE="background"
TEST_CONTAINER_TYPE="opengist"
TEST_CONTAINER_START_WAIT_SECONDS="10"

current_opengist_version() {
    get_config_arg ${UPSTREAM_OPENGIST_VERSION_CONFIG_KEY:?}
}

current_go_image_version() {
    get_config_arg ${UPSTREAM_GO_IMAGE_TAG_CONFIG_KEY:?}
}

current_nvm_version() {
    get_config_arg ${UPSTREAM_NVM_VERSION_CONFIG_KEY:?}
}

current_node_version() {
    get_config_arg ${UPSTREAM_NODEJS_VERSION_CONFIG_KEY:?}
}

current_upstream_version() {
    local opengist_ver="$(current_opengist_version)"
    local go_image_ver="$(current_go_image_version)"
    local nvm_ver="$(current_nvm_version)"
    local node_ver="$(current_node_version)"
    echo "${opengist_ver:?}/${go_image_ver:?}/${nvm_ver:?}/${node_ver:?}"
}

latest_opengist_version() {
    git -c 'versionsort.suffix=-' ls-remote \
        --exit-code \
        --refs \
        --sort='version:refname' \
        --tags \
        "${UPSTREAM_OPENGIST_GIT_REPO:?}" | \
        cut --delimiter='/' --fields=3 | \
        sort --version-sort --reverse | \
        head -1
}

latest_go_image_version() {
    dockerhub_latest_tag \
        "$(get_config_arg ${UPSTREAM_GO_IMAGE_NAME_CONFIG_KEY:?})" \
        "${UPSTREAM_GO_IMAGE_PATTERN:?}"
}

latest_nvm_version() {
    git_remote_repo_latest_tag "${UPSTREAM_NVM_GIT_REPO:?}"
}

latest_node_version() {
    curl --silent --fail --location --show-error https://nodejs.org/dist/index.tab | \
        tail -n+2 | \
        cut -d $'\t' -f '1,10' | \
        grep -v '-' | \
        cut -d $'\t' -f 1 | \
        sort --version-sort --reverse | \
        head -1
}

latest_upstream_version() {
    local opengist_ver="$(latest_opengist_version)"
    local go_image_ver="$(latest_go_image_version)"
    local nvm_ver="$(latest_nvm_version)"
    local node_ver="$(latest_node_version)"
    echo "${opengist_ver:?}/${go_image_ver:?}/${nvm_ver:?}/${node_ver:?}"
}

update_latest_upstream_version() {
    local cur_ver="${1:?}"
    local latest_ver="${2:?}"
    local cur_opengist_ver="$(echo "${cur_ver:?}" | cut -d '/' -f 1)"
    local cur_go_ver="$(echo "${cur_ver:?}" | cut -d '/' -f 2)"
    local cur_nvm_ver="$(echo "${cur_ver:?}" | cut -d '/' -f 3)"
    local cur_node_ver="$(echo "${cur_ver:?}" | cut -d '/' -f 4)"
    local latest_opengist_ver="$(echo "${latest_ver:?}" | cut -d '/' -f 1)"
    local latest_go_ver="$(echo "${latest_ver:?}" | cut -d '/' -f 2)"
    local latest_nvm_ver="$(echo "${latest_ver:?}" | cut -d '/' -f 3)"
    local latest_node_ver="$(echo "${latest_ver:?}" | cut -d '/' -f 4)"
    local latest_nvm_sha256_checksum="$(github_repo_archive_sha256_checksum ${UPSTREAM_NVM_GIT_REPO:?} ${latest_nvm_ver:?})"

    echo "Updating ${UPSTREAM_PACKAGE_NAME:?} ${UPSTREAM_OPENGIST_VERSION_CONFIG_KEY:?}/${UPSTREAM_GO_IMAGE_TAG_CONFIG_KEY}/${UPSTREAM_NVM_VERSION_CONFIG_KEY:?}/${UPSTREAM_NODEJS_VERSION_CONFIG_KEY:?} '${cur_ver:?}' -> '${latest_ver:?}'"
    set_config_arg "${UPSTREAM_OPENGIST_VERSION_CONFIG_KEY:?}" "${latest_opengist_ver:?}"
    set_config_arg "${UPSTREAM_GO_IMAGE_TAG_CONFIG_KEY:?}" "${latest_go_ver:?}"
    set_config_arg "${UPSTREAM_NVM_VERSION_CONFIG_KEY:?}" "${latest_nvm_ver:?}"
    set_config_arg "${UPSTREAM_NVM_CHECKSUM_CONFIG_KEY:?}" "${latest_nvm_sha256_checksum:?}"
    set_config_arg "${UPSTREAM_NODEJS_VERSION_CONFIG_KEY:?}" "${latest_node_ver:?}"
    git add ${ARGS_FILE:?}
}

package_current_release_version() {
    get_config_arg "${RELEASE_PACKAGE_VERSION_CONFIG_KEY:?}"
}

test_start_container() {
    local container_name="${1:?}"

    docker run \
        --name ${container_name:?} \
        --detach \
        --rm \
        ${IMAGE:?}
}

test_image_after_container_startup() {
    local container_name="${1:?}"
    local ip="$(container_ip "${container_name:?}")"
    test_http_endpoint "${container_name:?}" http ${ip:?} 6157
}
